// SPDX-License-Identifier: Apache-2.0

import {
  calculatedResult,
  type CalculationResult
} from "../core/calculation-result.js";
import { InvalidScientificInputError } from "../core/validation.js";

function requireNonNegativeFinite(name: string, value: number): void {
  if (!Number.isFinite(value) || value < 0) {
    throw new InvalidScientificInputError(
      `${name} must be a finite number greater than or equal to zero.`
    );
  }
}

export interface CalculatePhotoelectronsInput {
  /** Mean photons incident on the photosite/measurement region. */
  incidentPhotons: number;
  /** Quantum efficiency from 0 to 1 inclusive. */
  quantumEfficiency: number;
}

/**
 * Converts mean incident photon count to mean photoelectron count.
 *
 * This is an expectation value; the stochastic shot-noise realization is not
 * generated by this deterministic calculation.
 */
export function calculatePhotoelectrons(
  input: CalculatePhotoelectronsInput
): CalculationResult<number> {
  requireNonNegativeFinite("incidentPhotons", input.incidentPhotons);

  if (
    !Number.isFinite(input.quantumEfficiency) ||
    input.quantumEfficiency < 0 ||
    input.quantumEfficiency > 1
  ) {
    throw new InvalidScientificInputError(
      "quantumEfficiency must be a finite number from 0 through 1."
    );
  }

  return calculatedResult(
    input.incidentPhotons * input.quantumEfficiency,
    "mean-photoelectron-conversion",
    "1.0.0",
    ["Quantum efficiency is supplied by the caller"]
  );
}

export interface CalculateSignalToNoiseInput {
  /** Mean signal in electrons. */
  signalElectrons: number;
  /** RMS read noise in electrons. */
  readNoiseElectrons: number;
}

export interface SignalToNoise {
  shotNoiseStdElectrons: number;
  combinedNoiseStdElectrons: number;
  snrLinear: number;
  /** Null when the signal is zero because -Infinity dB is not JSON-safe. */
  snrDb: number | null;
}

/**
 * Calculates expected SNR from Poisson shot noise and independent RMS read
 * noise.
 *
 * Variances are combined as signalElectrons + readNoiseElectrons^2.
 * Dark current, fixed-pattern noise, quantization, clipping, and downstream
 * processing are intentionally outside this primitive.
 */
export function calculateSignalToNoise(
  input: CalculateSignalToNoiseInput
): CalculationResult<SignalToNoise> {
  requireNonNegativeFinite("signalElectrons", input.signalElectrons);
  requireNonNegativeFinite("readNoiseElectrons", input.readNoiseElectrons);

  const shotNoiseStdElectrons = Math.sqrt(input.signalElectrons);
  const combinedNoiseStdElectrons = Math.sqrt(
    input.signalElectrons +
      input.readNoiseElectrons * input.readNoiseElectrons
  );
  const snrLinear =
    combinedNoiseStdElectrons === 0
      ? 0
      : input.signalElectrons / combinedNoiseStdElectrons;
  const snrDb = snrLinear === 0 ? null : 20 * Math.log10(snrLinear);

  return calculatedResult(
    {
      shotNoiseStdElectrons,
      combinedNoiseStdElectrons,
      snrLinear,
      snrDb
    },
    "poisson-shot-plus-read-noise-snr",
    "1.0.0",
    [
      "Photon shot noise is Poisson",
      "Read noise is supplied as independent RMS electrons",
      "Dark current and fixed-pattern noise are not included"
    ]
  );
}
